### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by weujieytt** [inbug-team/Log4j_RCE_Tool#2]
post的参数加了url编码，payload参数只能用在vulfocus靶场 😥 可以做成匹配参数吗

![image](https://user-images.githubusercontent.com/70327097/145664285-5a8b413b-2bee-425a-bae7-6688cc435fe7.png)

**Comment by sinlee1** [comment]
- 0.2版本问题依然存在

![image](https://user-images.githubusercontent.com/29684167/145679771-3dce8592-91cf-41d3-b1f9-c3517a4dd499.png)

**Comment by inbug-team** [comment]
已更新v1.0版本
