### ISSUE TITLE
没办法扫描

### ISSUE THREAD

**Issue by JanyXian** [inbug-team/Log4j_RCE_Tool#5]
![image](https://user-images.githubusercontent.com/35955534/146122847-220be0b2-77a2-4803-8281-9f94fffe3036.png)

**Comment by inbug-team** [comment]
1、确认rad版本是否可用。
2、靶场没有可爬的参数，可以换个有参数的站点进行测试。

**Comment by JanyXian** [comment]
直接调用rad是没问题

**Comment by inbug-team** [comment]
因为配置文件过滤了html/js/css等，添加目标的时候不带html尝试一下，如果还不行，替换一下rad的版本。
